name: Build and Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew assembleDebug --no-daemon --stacktrace
      
    - name: Run unit tests
      run: ./gradlew :TeamCode:test --no-daemon --stacktrace
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          TeamCode/build/test-results/
          TeamCode/build/reports/tests/
        retention-days: 30
        
    - name: Publish test report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Test Results
        path: 'TeamCode/build/test-results/**/TEST-*.xml'
        reporter: java-junit
        fail-on-error: false
        
    - name: Comment test results on PR
      if: github.event_name == 'pull_request' && always()
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: 'TeamCode/build/test-results/**/TEST-*.xml'
        check_name: 'Unit Test Results'
        comment_title: 'Unit Test Results'
